# .github/workflows/ci-base.yml
name: Build and deploy ASP.Net Core app to Azure Web App - GustosApp

on:
  workflow_call:   # <- clave: habilita que otros workflows lo llamen
    inputs:
      run-docker:
        description: "Run docker step?"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Clean and restore
        run: |
          dotnet clean
          dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.run-docker }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/gustosapp:latest .

      - name: Push image to ACR
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/gustosapp:latest
